// ASSUMING 4 KB PAGE SIZE
#define PAGE_SIZE 4096

// ASSUMING VIRTUAL MEMORY SIZE 4GB
#define VIRTUAL_MEM_SIZE (1ULL << 32)

// ASSUMING THE PHYSICAL MEMORY SIZE 4GB
#define PHYSICAL_MEM_SIZE (1ULL << 32)

// ASSUMING THE MULTI LEVEL PAGE SIZE OF 1KB
#define PAGE_TABLE_LEVEL_2_SIZE 1024
#define PAGE_TABLE_LEVEL_3_SIZE 1024
